language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-favicons
    branch: publish
  api_key:
    secure: JT5yzy9HD731jBmc533s2ink7h2hK+B7EFWxsVYKLFDREn/guyjD42xVVj0qOvwZfUGVUjnpIZH5qvC81nkKB6ATulGYUBVSHkc53/4qa8U/HyASk76rga7gvRxKnIOX+qiig+4c7MZWNSaN+H8Lnmbqbii3J9u+8hLG85wlkqkTHvs4LUNs8nNtV78/ohsnV1h5291H9Yc/Z5SUgjRTBRxhcDOEGV2TcXsEodJjcsj1f0kd9Y8hwARwCxxrTLJsuy7EL5RFcchQc7zSjGkOYfutBQDKivwkVdJSDdNKD2tYLKmNDyf530gq6w05yF898i7SaTdOiQdLmmMjFwqTlnORpN2TAwUAmU6YTVrUuegCVsHzZU3JE60wR1gKPfaNiiCjnAv8r1urUnxiMN93df7T5+Oom7gTbpsL2zhh13J99PP8ZOOX24eYzOvfjwKNKzHJfuSq4oTvcF7VVNOrB3utuU0BPpavvNm7vO161nIwOY4dn6xOA8dLLZUlasjMU99keqIB/imA8S6p2lUtPmo68wy6cZ9qTlSUemLPKufprGEzZS/eHWvtXmbyGwqG1GHfxnWH8Oz0/ugzwhkEN/bpW8L4WwgIYIEajS/I7LptDl0AngL6E7m4wCABt5Zy8cf1+Kk0tlSGfw0LGPkidT5prI06L7UqsWUUO3r6Pok=
